# Zadanie 1: Klasyfikacja binarna - Diagnoza raka piersi

In [16]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, StratifiedKFold,cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import f1_score, roc_auc_score
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, f_classif

from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

import optuna
import tqdm

In [32]:
data = pd.read_csv("../Data/wisconsin_breast_cancer.csv")
data.head()

,id,thickness,size,shape,adhesion,single,nuclei,chromatin,nucleoli,mitosis,class
0,1000025,5,1,1,1,2,1.0,3,1,1,0
1,1002945,5,4,4,5,7,10.0,3,2,1,0
2,1015425,3,1,1,1,2,2.0,3,1,1,0
3,1016277,6,8,8,1,3,4.0,3,7,1,0
4,1017023,4,1,1,3,2,1.0,3,1,1,0

In [33]:
data.shape

(699, 11)

In [34]:
data.isna().sum()

id            0
thickness     0
size          0
shape         0
adhesion      0
single        0
nuclei       16
chromatin     0
nucleoli      0
mitosis       0
class         0
dtype: int64

In [35]:
data['nuclei'] = pd.to_numeric(data['nuclei'], errors='coerce')

In [36]:
display(data[data['nuclei'].isna()])

,id,thickness,size,shape,adhesion,single,nuclei,chromatin,nucleoli,mitosis,class
23,1057013,8,4,5,1,2,NaN,7,3,1,1
40,1096800,6,6,6,9,6,NaN,7,8,1,0
139,1183246,1,1,1,1,1,NaN,2,1,1,0
145,1184840,1,1,3,1,2,NaN,2,1,1,0
158,1193683,1,1,2,1,3,NaN,1,1,1,0
164,1197510,5,1,1,1,2,NaN,3,1,1,0
235,1241232,3,1,4,1,2,NaN,3,1,1,0
249,169356,3,1,1,1,2,NaN,3,1,1,0
275,432809,3,1,3,1,2,NaN,2,1,1,0
292,563649,8,8,8,1,2,NaN,6,10,1,1
294,606140,1,1,1,1,2,NaN,2,1,1,0
297,61634,5,4,3,1,2,NaN,2,3,1,0
315,704168,4,6,5,6,7,NaN,4,9,1,0
321,733639,3,1,1,1,2,NaN,3,1,1,0
411,1238464,1,1,1,1,1,NaN,2,1,1,0
617,1057067,1,1,1,1,1,NaN,1,1,1,0

In [37]:
data['nuclei'].fillna(data['nuclei'].median(), inplace=True)
data.isna().sum()

C:\Users\posze\AppData\Local\Temp\ipykernel_6436\2179343237.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['nuclei'].fillna(data['nuclei'].median(), inplace=True)

id           0
thickness    0
size         0
shape        0
adhesion     0
single       0
nuclei       0
chromatin    0
nucleoli     0
mitosis      0
class        0
dtype: int64

In [38]:
X = data.drop(['id','class'],axis=1)
y = data['class']

In [39]:
X_train1,X_val,y_train1,y_val = train_test_split(X,y,test_size=.2,shuffle=False,random_state=42)

In [48]:
def best_model_creator(X_train,y_train,model_name):
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    def objective(trial:optuna.trial.Trial):
        n_features = trial.suggest_int("n_features",3,X_train.shape[1])

        if model_name == "LR":
            penalty = trial.suggest_categorical('penalty',[None,'l2','l1'])

            if penalty == 'l1':
                solver = 'liblinear'
            else:
                solver = 'lbfgs'

            model = LogisticRegression(penalty=penalty,solver=solver)
        elif model_name == "KNN":
            n_neighbors = trial.suggest_int("n_neighbors",3,5)
            weights = trial.suggest_categorical("weights",['uniform','distance'])
            model = KNeighborsClassifier(n_neighbors=n_neighbors,weights=weights)

        pipeline = Pipeline([
            ("StandardScaler",StandardScaler()),
            ("SelectKBest",SelectKBest(k=n_features,score_func=f_classif)),
            ("Classifier",model)
        ])

        scores = cross_val_score(
            pipeline,
            X_train,
            y_train,
            cv=skf,
            scoring="roc_auc"
        )

        return scores.mean()
    
    study = optuna.create_study(direction="maximize")
    study.optimize(objective,n_trials=30)

    return study.best_params,study.best_value

In [49]:
val_cv = StratifiedKFold(n_splits=5,shuffle=True)

In [52]:
results = {
    "accuracy_lr": [],
    "accuracy_knn": [],
    "precission_lr": [],
    "precission_knn": [],
    "recall_lr": [],
    "recall_knn": [],
    "f1_lr": [],
    "f1_knn": [],
}

In [53]:
fold_idx = 0

for train_idx,test_idx in val_cv.split(X_train1,y_train1):
    fold_idx += 1
    X_train,X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train,y_test = y.iloc[train_idx], y.iloc[test_idx]

    best_params_lr,best_score_lr = best_model_creator(X_train,y_train,"LR")

    pipeline = Pipeline([
        ("StandardScaler",StandardScaler()),
        ("SelectKBest",SelectKBest(k=best_params_lr["n_features"],score_func=f_classif)),
        ("classificator", LogisticRegression(
            penalty=best_params_lr["penalty"],
            solver='liblinear' if best_params_lr["penalty"]=='l1' else 'lbfgs'
        ))
    ])

    pipeline.fit(X_train,y_train)
    preds_lr = pipeline.predict(X_test)

    TP = np.sum((preds_lr == 1) & (y_test == 1))
    TN = np.sum((preds_lr == 0) & (y_test == 0))
    FP = np.sum((preds_lr == 1) & (y_test == 0))
    FN = np.sum((preds_lr == 0) & (y_test == 1))

    accuracy = (TP + TN) / (TP + TN + FP + FN)
    precission = TP / (TP + FP)
    recall = TP / (TP + FN)
    f1 = f1_score(y_test,preds_lr)
    
    results["accuracy_lr"].append(accuracy)
    results["precission_lr"].append(precission)
    results["recall_lr"].append(recall)
    results["f1_lr"].append(f1)


    best_params_knn,best_score_knn = best_model_creator(X_train,y_train,"KNN")
    pipeline = Pipeline([
        ("StandardScaler",StandardScaler()),
        ("SelectKBest",SelectKBest(k=best_params_knn["n_features"],score_func=f_classif)),
        ("classificator", KNeighborsClassifier(
            n_neighbors=best_params_knn["n_neighbors"],
            weights=best_params_knn["weights"]
        ))
    ])
    pipeline.fit(X_train,y_train)
    preds_knn = pipeline.predict(X_test)

    TP = np.sum((preds_knn == 1) & (y_test == 1))
    TN = np.sum((preds_knn == 0) & (y_test == 0))
    FP = np.sum((preds_knn == 1) & (y_test == 0))
    FN = np.sum((preds_knn == 0) & (y_test == 1))

    accuracy = (TP + TN) / (TP + TN + FP + FN)
    precission = TP / (TP + FP)
    recall = TP / (TP + FN)
    f1 = f1_score(y_test,preds_knn)

    results["accuracy_knn"].append(accuracy)
    results["precission_knn"].append(precission)
    results["recall_knn"].append(recall)
    results["f1_knn"].append(f1)
    print(f"Fold {fold_idx} completed.")

for key in results.keys():
    results[key] = np.mean(results[key])

results

[I 2025-11-24 20:38:48,831] A new study created in memory with name: no-name-daedff0e-2f3b-469f-9bfb-c661daa6677e
[I 2025-11-24 20:38:48,896] Trial 0 finished with value: 0.9921831092883725 and parameters: {'n_features': 3, 'penalty': None}. Best is trial 0 with value: 0.9921831092883725.
[I 2025-11-24 20:38:48,949] Trial 1 finished with value: 0.9933602946760841 and parameters: {'n_features': 7, 'penalty': 'l2'}. Best is trial 1 with value: 0.9933602946760841.
[I 2025-11-24 20:38:48,985] Trial 2 finished with value: 0.9931457431457431 and parameters: {'n_features': 8, 'penalty': 'l1'}. Best is trial 1 with value: 0.9933602946760841.
[I 2025-11-24 20:38:49,035] Trial 3 finished with value: 0.9930375180375179 and parameters: {'n_features': 7, 'penalty': 'l1'}. Best is trial 1 with value: 0.9933602946760841.
[I 2025-11-24 20:38:49,114] Trial 4 finished with value: 0.9922875370243792 and parameters: {'n_features': 6, 'penalty': None}. Best is trial 1 with value: 0.9933602946760841.
[I 2025-11-24 20:38:49,154] Trial 5 finished with value: 0.9922932330827068 and parameters: {'n_features': 3, 'penalty': 'l1'}. Best is trial 1 with value: 0.9933602946760841.
[I 2025-11-24 20:38:49,226] Trial 6 finished with value: 0.9936849700007595 and parameters: {'n_features': 4, 'penalty': None}. Best is trial 6 with value: 0.9936849700007595.
[I 2025-11-24 20:38:49,290] Trial 7 finished with value: 0.9929292929292929 and parameters: {'n_features': 6, 'penalty': 'l1'}. Best is trial 6 with value: 0.9936849700007595.
[I 2025-11-24 20:38:49,362] Trial 8 finished with value: 0.9934685197843093 and parameters: {'n_features': 8, 'penalty': 'l2'}. Best is trial 6 with value: 0.9936849700007595.
[I 2025-11-24 20:38:49,413] Trial 9 finished with value: 0.9933564973038658 and parameters: {'n_features': 9, 'penalty': 'l1'}. Best is trial 6 with value: 0.9936849700007595.
[I 2025-11-24 20:38:49,490] Trial 10 finished with value: 0.9936849700007595 and parameters: {'n_features': 4, 'penalty': None}. Best is trial 6 with value: 0.9936849700007595.
[I 2025-11-24 20:38:49,551] Trial 11 finished with value: 0.9936849700007595 and parameters: {'n_features': 4, 'penalty': None}. Best is trial 6 with value: 0.9936849700007595.
[I 2025-11-24 20:38:49,609] Trial 12 finished with value: 0.9925039872408293 and parameters: {'n_features': 5, 'penalty': None}. Best is trial 6 with value: 0.9936849700007595.
[I 2025-11-24 20:38:49,675] Trial 13 finished with value: 0.9936849700007595 and parameters: {'n_features': 4, 'penalty': None}. Best is trial 6 with value: 0.9936849700007595.
[I 2025-11-24 20:38:49,732] Trial 14 finished with value: 0.9936849700007595 and parameters: {'n_features': 4, 'penalty': None}. Best is trial 6 with value: 0.9936849700007595.
[I 2025-11-24 20:38:49,801] Trial 15 finished with value: 0.9925039872408293 and parameters: {'n_features': 5, 'penalty': None}. Best is trial 6 with value: 0.9936849700007595.
[I 2025-11-24 20:38:49,887] Trial 16 finished with value: 0.9925039872408293 and parameters: {'n_features': 5, 'penalty': None}. Best is trial 6 with value: 0.9936849700007595.
[I 2025-11-24 20:38:49,954] Trial 17 finished with value: 0.9925077846130478 and parameters: {'n_features': 3, 'penalty': 'l2'}. Best is trial 6 with value: 0.9936849700007595.
[I 2025-11-24 20:38:50,041] Trial 18 finished with value: 0.9936849700007595 and parameters: {'n_features': 4, 'penalty': None}. Best is trial 6 with value: 0.9936849700007595.
[I 2025-11-24 20:38:50,108] Trial 19 finished with value: 0.9925039872408293 and parameters: {'n_features': 5, 'penalty': None}. Best is trial 6 with value: 0.9936849700007595.
[I 2025-11-24 20:38:50,161] Trial 20 finished with value: 0.9925077846130478 and parameters: {'n_features': 3, 'penalty': 'l2'}. Best is trial 6 with value: 0.9936849700007595.
[I 2025-11-24 20:38:50,233] Trial 21 finished with value: 0.9936849700007595 and parameters: {'n_features': 4, 'penalty': None}. Best is trial 6 with value: 0.9936849700007595.
[I 2025-11-24 20:38:50,301] Trial 22 finished with value: 0.9936849700007595 and parameters: {'n_features': 4, 'penalty': None}. Best is trial 6 with value: 0.9936849700007595.
[I 2025-11-24 20:38:50,361] Trial 23 finished with value: 0.9925039872408293 and parameters: {'n_features': 5, 'penalty': None}. Best is trial 6 with value: 0.9936849700007595.
[I 2025-11-24 20:38:50,432] Trial 24 finished with value: 0.9936849700007595 and parameters: {'n_features': 4, 'penalty': None}. Best is trial 6 with value: 0.9936849700007595.
[I 2025-11-24 20:38:50,482] Trial 25 finished with value: 0.9922875370243792 and parameters: {'n_features': 6, 'penalty': None}. Best is trial 6 with value: 0.9936849700007595.
[I 2025-11-24 20:38:50,538] Trial 26 finished with value: 0.9921831092883725 and parameters: {'n_features': 3, 'penalty': None}. Best is trial 6 with value: 0.9936849700007595.
[I 2025-11-24 20:38:50,608] Trial 27 finished with value: 0.9925039872408293 and parameters: {'n_features': 5, 'penalty': None}. Best is trial 6 with value: 0.9936849700007595.
[I 2025-11-24 20:38:50,669] Trial 28 finished with value: 0.9940096453254347 and parameters: {'n_features': 4, 'penalty': 'l2'}. Best is trial 28 with value: 0.9940096453254347.
[I 2025-11-24 20:38:50,728] Trial 29 finished with value: 0.9925077846130478 and parameters: {'n_features': 3, 'penalty': 'l2'}. Best is trial 28 with value: 0.9940096453254347.
[I 2025-11-24 20:38:50,742] A new study created in memory with name: no-name-03388917-90b7-4d92-add4-6d2caf1d0200
[I 2025-11-24 20:38:50,787] Trial 0 finished with value: 0.9638176881597935 and parameters: {'n_features': 3, 'n_neighbors': 3, 'weights': 'distance'}. Best is trial 0 with value: 0.9638176881597935.
[I 2025-11-24 20:38:50,835] Trial 1 finished with value: 0.9829184704184705 and parameters: {'n_features': 8, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 1 with value: 0.9829184704184705.
[I 2025-11-24 20:38:50,886] Trial 2 finished with value: 0.9785723779144831 and parameters: {'n_features': 9, 'n_neighbors': 3, 'weights': 'distance'}. Best is trial 1 with value: 0.9829184704184705.
[I 2025-11-24 20:38:50,934] Trial 3 finished with value: 0.9788970532391584 and parameters: {'n_features': 9, 'n_neighbors': 3, 'weights': 'uniform'}. Best is trial 1 with value: 0.9829184704184705.
[I 2025-11-24 20:38:50,980] Trial 4 finished with value: 0.9748243715348979 and parameters: {'n_features': 6, 'n_neighbors': 3, 'weights': 'distance'}. Best is trial 1 with value: 0.9829184704184705.
[I 2025-11-24 20:38:51,023] Trial 5 finished with value: 0.9797951317688159 and parameters: {'n_features': 5, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 1 with value: 0.9829184704184705.
[I 2025-11-24 20:38:51,075] Trial 6 finished with value: 0.9739699627857522 and parameters: {'n_features': 6, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 1 with value: 0.9829184704184705.
[I 2025-11-24 20:38:51,116] Trial 7 finished with value: 0.9668422951317688 and parameters: {'n_features': 3, 'n_neighbors': 4, 'weights': 'distance'}. Best is trial 1 with value: 0.9829184704184705.
[I 2025-11-24 20:38:51,173] Trial 8 finished with value: 0.9638176881597935 and parameters: {'n_features': 3, 'n_neighbors': 3, 'weights': 'distance'}. Best is trial 1 with value: 0.9829184704184705.
[I 2025-11-24 20:38:51,224] Trial 9 finished with value: 0.9843159033948508 and parameters: {'n_features': 9, 'n_neighbors': 4, 'weights': 'distance'}. Best is trial 9 with value: 0.9843159033948508.
[I 2025-11-24 20:38:51,273] Trial 10 finished with value: 0.9828140426824638 and parameters: {'n_features': 8, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 9 with value: 0.9843159033948508.
[I 2025-11-24 20:38:51,319] Trial 11 finished with value: 0.9829184704184705 and parameters: {'n_features': 8, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 9 with value: 0.9843159033948508.
[I 2025-11-24 20:38:51,363] Trial 12 finished with value: 0.9829184704184705 and parameters: {'n_features': 8, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 9 with value: 0.9843159033948508.
[I 2025-11-24 20:38:51,424] Trial 13 finished with value: 0.9850848712690817 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 13 with value: 0.9850848712690817.
[I 2025-11-24 20:38:51,479] Trial 14 finished with value: 0.9826735399103821 and parameters: {'n_features': 7, 'n_neighbors': 4, 'weights': 'distance'}. Best is trial 13 with value: 0.9850848712690817.
[I 2025-11-24 20:38:51,536] Trial 15 finished with value: 0.9797951317688159 and parameters: {'n_features': 5, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 13 with value: 0.9850848712690817.
[I 2025-11-24 20:38:51,594] Trial 16 finished with value: 0.9850848712690817 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 13 with value: 0.9850848712690817.
[I 2025-11-24 20:38:51,643] Trial 17 finished with value: 0.9850848712690817 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 13 with value: 0.9850848712690817.
[I 2025-11-24 20:38:51,695] Trial 18 finished with value: 0.983201374648743 and parameters: {'n_features': 5, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 13 with value: 0.9850848712690817.
[I 2025-11-24 20:38:51,751] Trial 19 finished with value: 0.9850848712690817 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 13 with value: 0.9850848712690817.
[I 2025-11-24 20:38:51,808] Trial 20 finished with value: 0.9812903470798208 and parameters: {'n_features': 4, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 13 with value: 0.9850848712690817.
[I 2025-11-24 20:38:51,849] Trial 21 finished with value: 0.9850848712690817 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 13 with value: 0.9850848712690817.
[I 2025-11-24 20:38:51,889] Trial 22 finished with value: 0.9850070251386042 and parameters: {'n_features': 6, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 13 with value: 0.9850848712690817.
[I 2025-11-24 20:38:51,943] Trial 23 finished with value: 0.9850848712690817 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 13 with value: 0.9850848712690817.
[I 2025-11-24 20:38:51,999] Trial 24 finished with value: 0.9850070251386042 and parameters: {'n_features': 6, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 13 with value: 0.9850848712690817.
[I 2025-11-24 20:38:52,050] Trial 25 finished with value: 0.9850848712690817 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 13 with value: 0.9850848712690817.
[I 2025-11-24 20:38:52,099] Trial 26 finished with value: 0.9829184704184705 and parameters: {'n_features': 8, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 13 with value: 0.9850848712690817.
[I 2025-11-24 20:38:52,145] Trial 27 finished with value: 0.9739699627857522 and parameters: {'n_features': 6, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 13 with value: 0.9850848712690817.
[I 2025-11-24 20:38:52,191] Trial 28 finished with value: 0.9850848712690817 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 13 with value: 0.9850848712690817.
[I 2025-11-24 20:38:52,254] Trial 29 finished with value: 0.9820498215235057 and parameters: {'n_features': 8, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 13 with value: 0.9850848712690817.
[I 2025-11-24 20:38:52,274] A new study created in memory with name: no-name-19345a58-0576-4a39-9a7f-4740d8b7a9d6
[I 2025-11-24 20:38:52,358] Trial 0 finished with value: 0.9869522290574922 and parameters: {'n_features': 3, 'penalty': None}. Best is trial 0 with value: 0.9869522290574922.
[I 2025-11-24 20:38:52,428] Trial 1 finished with value: 0.9896065922381713 and parameters: {'n_features': 7, 'penalty': 'l2'}. Best is trial 1 with value: 0.9896065922381713.

Fold 1 completed.

[I 2025-11-24 20:38:52,469] Trial 2 finished with value: 0.9891774891774892 and parameters: {'n_features': 6, 'penalty': 'l1'}. Best is trial 1 with value: 0.9896065922381713.
[I 2025-11-24 20:38:52,548] Trial 3 finished with value: 0.9885281385281385 and parameters: {'n_features': 9, 'penalty': None}. Best is trial 1 with value: 0.9896065922381713.
[I 2025-11-24 20:38:52,597] Trial 4 finished with value: 0.9867395762132605 and parameters: {'n_features': 3, 'penalty': 'l1'}. Best is trial 1 with value: 0.9896065922381713.
[I 2025-11-24 20:38:52,660] Trial 5 finished with value: 0.9900394926710716 and parameters: {'n_features': 9, 'penalty': 'l2'}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:52,710] Trial 6 finished with value: 0.9877762588288904 and parameters: {'n_features': 5, 'penalty': 'l2'}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:52,747] Trial 7 finished with value: 0.9867395762132605 and parameters: {'n_features': 3, 'penalty': 'l1'}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:52,785] Trial 8 finished with value: 0.9896160856687171 and parameters: {'n_features': 9, 'penalty': 'l1'}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:52,834] Trial 9 finished with value: 0.9894926710716184 and parameters: {'n_features': 6, 'penalty': 'l2'}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:52,883] Trial 10 finished with value: 0.989281916913496 and parameters: {'n_features': 8, 'penalty': 'l2'}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:52,929] Trial 11 finished with value: 0.9896160856687171 and parameters: {'n_features': 9, 'penalty': 'l1'}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:52,988] Trial 12 finished with value: 0.989281916913496 and parameters: {'n_features': 8, 'penalty': 'l2'}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:53,053] Trial 13 finished with value: 0.988962937647148 and parameters: {'n_features': 8, 'penalty': 'l1'}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:53,123] Trial 14 finished with value: 0.9885281385281385 and parameters: {'n_features': 9, 'penalty': None}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:53,182] Trial 15 finished with value: 0.9896065922381713 and parameters: {'n_features': 7, 'penalty': 'l2'}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:53,236] Trial 16 finished with value: 0.9877781575149995 and parameters: {'n_features': 5, 'penalty': 'l1'}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:53,304] Trial 17 finished with value: 0.9900394926710716 and parameters: {'n_features': 9, 'penalty': 'l2'}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:53,367] Trial 18 finished with value: 0.9896065922381713 and parameters: {'n_features': 7, 'penalty': 'l2'}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:53,426] Trial 19 finished with value: 0.989281916913496 and parameters: {'n_features': 8, 'penalty': 'l2'}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:53,483] Trial 20 finished with value: 0.9877762588288904 and parameters: {'n_features': 5, 'penalty': 'l2'}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:53,546] Trial 21 finished with value: 0.9900394926710716 and parameters: {'n_features': 9, 'penalty': 'l2'}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:53,604] Trial 22 finished with value: 0.9900394926710716 and parameters: {'n_features': 9, 'penalty': 'l2'}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:53,664] Trial 23 finished with value: 0.989281916913496 and parameters: {'n_features': 8, 'penalty': 'l2'}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:53,719] Trial 24 finished with value: 0.9900394926710716 and parameters: {'n_features': 9, 'penalty': 'l2'}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:53,776] Trial 25 finished with value: 0.9896065922381713 and parameters: {'n_features': 7, 'penalty': 'l2'}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:53,845] Trial 26 finished with value: 0.9879908103592314 and parameters: {'n_features': 8, 'penalty': None}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:53,902] Trial 27 finished with value: 0.9900394926710716 and parameters: {'n_features': 9, 'penalty': 'l2'}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:53,953] Trial 28 finished with value: 0.9888680033416876 and parameters: {'n_features': 4, 'penalty': 'l2'}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:54,004] Trial 29 finished with value: 0.9879908103592314 and parameters: {'n_features': 8, 'penalty': None}. Best is trial 5 with value: 0.9900394926710716.
[I 2025-11-24 20:38:54,013] A new study created in memory with name: no-name-aec50713-a8ee-4833-9295-1b92b64c6dab
[I 2025-11-24 20:38:54,057] Trial 0 finished with value: 0.9671308954203692 and parameters: {'n_features': 4, 'n_neighbors': 3, 'weights': 'uniform'}. Best is trial 0 with value: 0.9671308954203692.
[I 2025-11-24 20:38:54,104] Trial 1 finished with value: 0.9733111187058554 and parameters: {'n_features': 8, 'n_neighbors': 3, 'weights': 'distance'}. Best is trial 1 with value: 0.9733111187058554.
[I 2025-11-24 20:38:54,148] Trial 2 finished with value: 0.9775936052251843 and parameters: {'n_features': 8, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 2 with value: 0.9775936052251843.
[I 2025-11-24 20:38:54,193] Trial 3 finished with value: 0.9757328928381559 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 2 with value: 0.9775936052251843.
[I 2025-11-24 20:38:54,237] Trial 4 finished with value: 0.9733111187058554 and parameters: {'n_features': 8, 'n_neighbors': 3, 'weights': 'distance'}. Best is trial 2 with value: 0.9775936052251843.
[I 2025-11-24 20:38:54,297] Trial 5 finished with value: 0.9693457127667653 and parameters: {'n_features': 7, 'n_neighbors': 3, 'weights': 'uniform'}. Best is trial 2 with value: 0.9775936052251843.
[I 2025-11-24 20:38:54,336] Trial 6 finished with value: 0.9595845674793043 and parameters: {'n_features': 5, 'n_neighbors': 3, 'weights': 'distance'}. Best is trial 2 with value: 0.9775936052251843.
[I 2025-11-24 20:38:54,377] Trial 7 finished with value: 0.9722962709804814 and parameters: {'n_features': 6, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 2 with value: 0.9775936052251843.
[I 2025-11-24 20:38:54,420] Trial 8 finished with value: 0.9707526391736918 and parameters: {'n_features': 3, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 2 with value: 0.9775936052251843.
[I 2025-11-24 20:38:54,467] Trial 9 finished with value: 0.9614614186982606 and parameters: {'n_features': 3, 'n_neighbors': 3, 'weights': 'distance'}. Best is trial 2 with value: 0.9775936052251843.
[I 2025-11-24 20:38:54,521] Trial 10 finished with value: 0.9781840966051492 and parameters: {'n_features': 9, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 10 with value: 0.9781840966051492.
[I 2025-11-24 20:38:54,588] Trial 11 finished with value: 0.9781840966051492 and parameters: {'n_features': 9, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 10 with value: 0.9781840966051492.
[I 2025-11-24 20:38:54,640] Trial 12 finished with value: 0.9781840966051492 and parameters: {'n_features': 9, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 10 with value: 0.9781840966051492.
[I 2025-11-24 20:38:54,692] Trial 13 finished with value: 0.9781840966051492 and parameters: {'n_features': 9, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 10 with value: 0.9781840966051492.
[I 2025-11-24 20:38:54,748] Trial 14 finished with value: 0.9781840966051492 and parameters: {'n_features': 9, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 10 with value: 0.9781840966051492.
[I 2025-11-24 20:38:54,813] Trial 15 finished with value: 0.9728146122882965 and parameters: {'n_features': 7, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 10 with value: 0.9781840966051492.
[I 2025-11-24 20:38:54,854] Trial 16 finished with value: 0.9718263461684515 and parameters: {'n_features': 6, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 10 with value: 0.9781840966051492.
[I 2025-11-24 20:38:54,902] Trial 17 finished with value: 0.9781840966051492 and parameters: {'n_features': 9, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 10 with value: 0.9781840966051492.
[I 2025-11-24 20:38:54,962] Trial 18 finished with value: 0.9771578567631198 and parameters: {'n_features': 8, 'n_neighbors': 4, 'weights': 'distance'}. Best is trial 10 with value: 0.9781840966051492.
[I 2025-11-24 20:38:55,014] Trial 19 finished with value: 0.9709282676387939 and parameters: {'n_features': 5, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 10 with value: 0.9781840966051492.
[I 2025-11-24 20:38:55,072] Trial 20 finished with value: 0.9722962709804814 and parameters: {'n_features': 6, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 10 with value: 0.9781840966051492.
[I 2025-11-24 20:38:55,123] Trial 21 finished with value: 0.9781840966051492 and parameters: {'n_features': 9, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 10 with value: 0.9781840966051492.
[I 2025-11-24 20:38:55,173] Trial 22 finished with value: 0.9781840966051492 and parameters: {'n_features': 9, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 10 with value: 0.9781840966051492.
[I 2025-11-24 20:38:55,225] Trial 23 finished with value: 0.9776989823042455 and parameters: {'n_features': 8, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 10 with value: 0.9781840966051492.
[I 2025-11-24 20:38:55,270] Trial 24 finished with value: 0.9781840966051492 and parameters: {'n_features': 9, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 10 with value: 0.9781840966051492.
[I 2025-11-24 20:38:55,317] Trial 25 finished with value: 0.9728146122882965 and parameters: {'n_features': 7, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 10 with value: 0.9781840966051492.
[I 2025-11-24 20:38:55,362] Trial 26 finished with value: 0.9783388395230501 and parameters: {'n_features': 8, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 26 with value: 0.9783388395230501.
[I 2025-11-24 20:38:55,404] Trial 27 finished with value: 0.9783388395230501 and parameters: {'n_features': 8, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 26 with value: 0.9783388395230501.
[I 2025-11-24 20:38:55,456] Trial 28 finished with value: 0.9783388395230501 and parameters: {'n_features': 8, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 26 with value: 0.9783388395230501.
[I 2025-11-24 20:38:55,518] Trial 29 finished with value: 0.9748784840890105 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 26 with value: 0.9783388395230501.
[I 2025-11-24 20:38:55,529] A new study created in memory with name: no-name-dacb63f1-00bb-4539-bd1e-23caeb2a759d
[I 2025-11-24 20:38:55,602] Trial 0 finished with value: 0.9917445127971444 and parameters: {'n_features': 7, 'penalty': 'l2'}. Best is trial 0 with value: 0.9917445127971444.
[I 2025-11-24 20:38:55,671] Trial 1 finished with value: 0.9900983519404573 and parameters: {'n_features': 3, 'penalty': 'l2'}. Best is trial 0 with value: 0.9917445127971444.

Fold 2 completed.

[I 2025-11-24 20:38:55,740] Trial 2 finished with value: 0.9901211361737678 and parameters: {'n_features': 4, 'penalty': None}. Best is trial 0 with value: 0.9917445127971444.
[I 2025-11-24 20:38:55,809] Trial 3 finished with value: 0.9924774056353005 and parameters: {'n_features': 5, 'penalty': 'l2'}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:55,869] Trial 4 finished with value: 0.9900394926710717 and parameters: {'n_features': 9, 'penalty': 'l2'}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:55,919] Trial 5 finished with value: 0.9898363332573858 and parameters: {'n_features': 9, 'penalty': 'l1'}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:55,978] Trial 6 finished with value: 0.9919476722108301 and parameters: {'n_features': 6, 'penalty': None}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:56,029] Trial 7 finished with value: 0.9898363332573858 and parameters: {'n_features': 9, 'penalty': 'l1'}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:56,087] Trial 8 finished with value: 0.9919495708969392 and parameters: {'n_features': 5, 'penalty': None}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:56,129] Trial 9 finished with value: 0.9900129110655426 and parameters: {'n_features': 4, 'penalty': 'l1'}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:56,192] Trial 10 finished with value: 0.9917445127971444 and parameters: {'n_features': 7, 'penalty': 'l2'}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:56,258] Trial 11 finished with value: 0.9919495708969392 and parameters: {'n_features': 5, 'penalty': None}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:56,315] Trial 12 finished with value: 0.9919495708969392 and parameters: {'n_features': 5, 'penalty': None}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:56,373] Trial 13 finished with value: 0.9919457735247208 and parameters: {'n_features': 6, 'penalty': 'l2'}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:56,436] Trial 14 finished with value: 0.9900983519404573 and parameters: {'n_features': 3, 'penalty': None}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:56,497] Trial 15 finished with value: 0.9924774056353005 and parameters: {'n_features': 5, 'penalty': 'l2'}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:56,554] Trial 16 finished with value: 0.9917445127971444 and parameters: {'n_features': 7, 'penalty': 'l2'}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:56,608] Trial 17 finished with value: 0.9907666894509 and parameters: {'n_features': 4, 'penalty': 'l2'}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:56,660] Trial 18 finished with value: 0.9924774056353005 and parameters: {'n_features': 5, 'penalty': 'l2'}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:56,718] Trial 19 finished with value: 0.9919457735247208 and parameters: {'n_features': 6, 'penalty': 'l2'}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:56,772] Trial 20 finished with value: 0.9904666970456443 and parameters: {'n_features': 8, 'penalty': 'l2'}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:56,827] Trial 21 finished with value: 0.9924774056353005 and parameters: {'n_features': 5, 'penalty': 'l2'}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:56,892] Trial 22 finished with value: 0.9907666894509 and parameters: {'n_features': 4, 'penalty': 'l2'}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:56,954] Trial 23 finished with value: 0.9919457735247208 and parameters: {'n_features': 6, 'penalty': 'l2'}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:57,020] Trial 24 finished with value: 0.9924774056353005 and parameters: {'n_features': 5, 'penalty': 'l2'}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:57,071] Trial 25 finished with value: 0.9901211361737678 and parameters: {'n_features': 4, 'penalty': 'l1'}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:57,133] Trial 26 finished with value: 0.9924774056353005 and parameters: {'n_features': 5, 'penalty': 'l2'}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:57,189] Trial 27 finished with value: 0.9900983519404573 and parameters: {'n_features': 3, 'penalty': 'l2'}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:57,264] Trial 28 finished with value: 0.9919457735247208 and parameters: {'n_features': 6, 'penalty': 'l2'}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:57,326] Trial 29 finished with value: 0.9917445127971444 and parameters: {'n_features': 7, 'penalty': 'l2'}. Best is trial 3 with value: 0.9924774056353005.
[I 2025-11-24 20:38:57,337] A new study created in memory with name: no-name-8a36c6da-dc33-444c-8a66-6a0bc6598a54
[I 2025-11-24 20:38:57,391] Trial 0 finished with value: 0.9794229892914104 and parameters: {'n_features': 8, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 0 with value: 0.9794229892914104.
[I 2025-11-24 20:38:57,439] Trial 1 finished with value: 0.9623927242348295 and parameters: {'n_features': 3, 'n_neighbors': 4, 'weights': 'distance'}. Best is trial 0 with value: 0.9794229892914104.
[I 2025-11-24 20:38:57,493] Trial 2 finished with value: 0.9744958988380041 and parameters: {'n_features': 5, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 0 with value: 0.9794229892914104.
[I 2025-11-24 20:38:57,547] Trial 3 finished with value: 0.9666343890028101 and parameters: {'n_features': 3, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 0 with value: 0.9794229892914104.
[I 2025-11-24 20:38:57,601] Trial 4 finished with value: 0.9765540745803903 and parameters: {'n_features': 6, 'n_neighbors': 4, 'weights': 'distance'}. Best is trial 0 with value: 0.9794229892914104.
[I 2025-11-24 20:38:57,662] Trial 5 finished with value: 0.9733766233766235 and parameters: {'n_features': 3, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 0 with value: 0.9794229892914104.
[I 2025-11-24 20:38:57,709] Trial 6 finished with value: 0.9794229892914104 and parameters: {'n_features': 8, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 0 with value: 0.9794229892914104.
[I 2025-11-24 20:38:57,755] Trial 7 finished with value: 0.9756142249563302 and parameters: {'n_features': 4, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 0 with value: 0.9794229892914104.
[I 2025-11-24 20:38:57,803] Trial 8 finished with value: 0.97309561783246 and parameters: {'n_features': 4, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 0 with value: 0.9794229892914104.
[I 2025-11-24 20:38:57,852] Trial 9 finished with value: 0.9784622541201488 and parameters: {'n_features': 8, 'n_neighbors': 3, 'weights': 'distance'}. Best is trial 0 with value: 0.9794229892914104.
[I 2025-11-24 20:38:57,910] Trial 10 finished with value: 0.96991341991342 and parameters: {'n_features': 9, 'n_neighbors': 3, 'weights': 'uniform'}. Best is trial 0 with value: 0.9794229892914104.
[I 2025-11-24 20:38:57,962] Trial 11 finished with value: 0.9794229892914104 and parameters: {'n_features': 8, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 0 with value: 0.9794229892914104.
[I 2025-11-24 20:38:58,005] Trial 12 finished with value: 0.9813681932102984 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 12 with value: 0.9813681932102984.
[I 2025-11-24 20:38:58,059] Trial 13 finished with value: 0.9813681932102984 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 12 with value: 0.9813681932102984.
[I 2025-11-24 20:38:58,124] Trial 14 finished with value: 0.9767752715121135 and parameters: {'n_features': 6, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 12 with value: 0.9813681932102984.
[I 2025-11-24 20:38:58,179] Trial 15 finished with value: 0.9813681932102984 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 12 with value: 0.9813681932102984.
[I 2025-11-24 20:38:58,239] Trial 16 finished with value: 0.9813681932102984 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 12 with value: 0.9813681932102984.
[I 2025-11-24 20:38:58,281] Trial 17 finished with value: 0.9796755145439355 and parameters: {'n_features': 7, 'n_neighbors': 4, 'weights': 'distance'}. Best is trial 12 with value: 0.9813681932102984.
[I 2025-11-24 20:38:58,323] Trial 18 finished with value: 0.96991341991342 and parameters: {'n_features': 9, 'n_neighbors': 3, 'weights': 'uniform'}. Best is trial 12 with value: 0.9813681932102984.
[I 2025-11-24 20:38:58,369] Trial 19 finished with value: 0.9744958988380041 and parameters: {'n_features': 5, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 12 with value: 0.9813681932102984.
[I 2025-11-24 20:38:58,424] Trial 20 finished with value: 0.9765540745803903 and parameters: {'n_features': 6, 'n_neighbors': 4, 'weights': 'distance'}. Best is trial 12 with value: 0.9813681932102984.
[I 2025-11-24 20:38:58,472] Trial 21 finished with value: 0.9813681932102984 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 12 with value: 0.9813681932102984.
[I 2025-11-24 20:38:58,527] Trial 22 finished with value: 0.9813681932102984 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 12 with value: 0.9813681932102984.
[I 2025-11-24 20:38:58,583] Trial 23 finished with value: 0.9772689299005088 and parameters: {'n_features': 6, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 12 with value: 0.9813681932102984.
[I 2025-11-24 20:38:58,668] Trial 24 finished with value: 0.9813681932102984 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 12 with value: 0.9813681932102984.
[I 2025-11-24 20:38:58,719] Trial 25 finished with value: 0.9744958988380041 and parameters: {'n_features': 5, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 12 with value: 0.9813681932102984.
[I 2025-11-24 20:38:58,757] Trial 26 finished with value: 0.9791467304625199 and parameters: {'n_features': 8, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 12 with value: 0.9813681932102984.
[I 2025-11-24 20:38:58,803] Trial 27 finished with value: 0.9772689299005088 and parameters: {'n_features': 6, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 12 with value: 0.9813681932102984.
[I 2025-11-24 20:38:58,863] Trial 28 finished with value: 0.9796755145439355 and parameters: {'n_features': 7, 'n_neighbors': 4, 'weights': 'distance'}. Best is trial 12 with value: 0.9813681932102984.
[I 2025-11-24 20:38:58,922] Trial 29 finished with value: 0.9787366142629301 and parameters: {'n_features': 9, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 12 with value: 0.9813681932102984.
[I 2025-11-24 20:38:58,936] A new study created in memory with name: no-name-064b6194-9d8b-4133-bbb8-b9540e4da6e1
[I 2025-11-24 20:38:58,988] Trial 0 finished with value: 0.9899654439128124 and parameters: {'n_features': 3, 'penalty': 'l1'}. Best is trial 0 with value: 0.9899654439128124.
[I 2025-11-24 20:38:59,047] Trial 1 finished with value: 0.9905032467532469 and parameters: {'n_features': 3, 'penalty': 'l2'}. Best is trial 1 with value: 0.9905032467532469.
[I 2025-11-24 20:38:59,112] Trial 2 finished with value: 0.9928419533682693 and parameters: {'n_features': 4, 'penalty': 'l2'}. Best is trial 2 with value: 0.9928419533682693.

Fold 3 completed.

[I 2025-11-24 20:38:59,187] Trial 3 finished with value: 0.995033986481355 and parameters: {'n_features': 9, 'penalty': 'l2'}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:38:59,250] Trial 4 finished with value: 0.9928419533682693 and parameters: {'n_features': 4, 'penalty': 'l2'}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:38:59,313] Trial 5 finished with value: 0.995033986481355 and parameters: {'n_features': 9, 'penalty': 'l2'}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:38:59,361] Trial 6 finished with value: 0.9948094668489406 and parameters: {'n_features': 9, 'penalty': 'l1'}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:38:59,402] Trial 7 finished with value: 0.9926278765094555 and parameters: {'n_features': 4, 'penalty': 'l1'}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:38:59,456] Trial 8 finished with value: 0.9920986177565124 and parameters: {'n_features': 5, 'penalty': None}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:38:59,511] Trial 9 finished with value: 0.9905032467532469 and parameters: {'n_features': 3, 'penalty': 'l2'}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:38:59,569] Trial 10 finished with value: 0.9934134578871422 and parameters: {'n_features': 7, 'penalty': None}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:38:59,628] Trial 11 finished with value: 0.995033986481355 and parameters: {'n_features': 9, 'penalty': 'l2'}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:38:59,684] Trial 12 finished with value: 0.9939455646692489 and parameters: {'n_features': 7, 'penalty': 'l2'}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:38:59,757] Trial 13 finished with value: 0.9938439849624061 and parameters: {'n_features': 8, 'penalty': 'l2'}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:38:59,839] Trial 14 finished with value: 0.9938439849624061 and parameters: {'n_features': 8, 'penalty': 'l2'}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:38:59,917] Trial 15 finished with value: 0.9934201032885245 and parameters: {'n_features': 8, 'penalty': None}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:38:59,982] Trial 16 finished with value: 0.9934993734335841 and parameters: {'n_features': 6, 'penalty': 'l2'}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:39:00,048] Trial 17 finished with value: 0.995033986481355 and parameters: {'n_features': 9, 'penalty': 'l2'}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:39:00,110] Trial 18 finished with value: 0.9934134578871422 and parameters: {'n_features': 7, 'penalty': None}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:39:00,165] Trial 19 finished with value: 0.9928504974557606 and parameters: {'n_features': 6, 'penalty': 'l1'}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:39:00,229] Trial 20 finished with value: 0.995033986481355 and parameters: {'n_features': 9, 'penalty': 'l2'}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:39:00,297] Trial 21 finished with value: 0.995033986481355 and parameters: {'n_features': 9, 'penalty': 'l2'}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:39:00,371] Trial 22 finished with value: 0.9938439849624061 and parameters: {'n_features': 8, 'penalty': 'l2'}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:39:00,446] Trial 23 finished with value: 0.995033986481355 and parameters: {'n_features': 9, 'penalty': 'l2'}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:39:00,506] Trial 24 finished with value: 0.9938439849624061 and parameters: {'n_features': 8, 'penalty': 'l2'}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:39:00,571] Trial 25 finished with value: 0.995033986481355 and parameters: {'n_features': 9, 'penalty': 'l2'}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:39:00,640] Trial 26 finished with value: 0.9939455646692489 and parameters: {'n_features': 7, 'penalty': 'l2'}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:39:00,713] Trial 27 finished with value: 0.9938439849624061 and parameters: {'n_features': 8, 'penalty': 'l2'}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:39:00,779] Trial 28 finished with value: 0.9925310435178856 and parameters: {'n_features': 6, 'penalty': None}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:39:00,835] Trial 29 finished with value: 0.9948094668489406 and parameters: {'n_features': 9, 'penalty': 'l1'}. Best is trial 3 with value: 0.995033986481355.
[I 2025-11-24 20:39:00,850] A new study created in memory with name: no-name-b3062a86-7275-44ca-a66e-d02342eb8115
[I 2025-11-24 20:39:00,907] Trial 0 finished with value: 0.9654847345636819 and parameters: {'n_features': 3, 'n_neighbors': 4, 'weights': 'distance'}. Best is trial 0 with value: 0.9654847345636819.
[I 2025-11-24 20:39:00,963] Trial 1 finished with value: 0.9888499658236501 and parameters: {'n_features': 6, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:01,020] Trial 2 finished with value: 0.9880354294827978 and parameters: {'n_features': 6, 'n_neighbors': 4, 'weights': 'distance'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:01,067] Trial 3 finished with value: 0.9858058973190552 and parameters: {'n_features': 6, 'n_neighbors': 3, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:01,117] Trial 4 finished with value: 0.9765070820991874 and parameters: {'n_features': 7, 'n_neighbors': 3, 'weights': 'distance'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:01,169] Trial 5 finished with value: 0.9851940457203614 and parameters: {'n_features': 5, 'n_neighbors': 4, 'weights': 'distance'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:01,221] Trial 6 finished with value: 0.987238455988456 and parameters: {'n_features': 8, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:01,267] Trial 7 finished with value: 0.9863489215462901 and parameters: {'n_features': 7, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:01,311] Trial 8 finished with value: 0.9654847345636819 and parameters: {'n_features': 3, 'n_neighbors': 4, 'weights': 'distance'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:01,363] Trial 9 finished with value: 0.9858500417710945 and parameters: {'n_features': 9, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:01,427] Trial 10 finished with value: 0.9813019765322398 and parameters: {'n_features': 4, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:01,479] Trial 11 finished with value: 0.9888499658236501 and parameters: {'n_features': 6, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:01,539] Trial 12 finished with value: 0.98730111263006 and parameters: {'n_features': 5, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:01,583] Trial 13 finished with value: 0.9872325225943648 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:01,630] Trial 14 finished with value: 0.98730111263006 and parameters: {'n_features': 5, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:01,692] Trial 15 finished with value: 0.987238455988456 and parameters: {'n_features': 8, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:01,756] Trial 16 finished with value: 0.9888499658236501 and parameters: {'n_features': 6, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:01,816] Trial 17 finished with value: 0.9793123908255488 and parameters: {'n_features': 4, 'n_neighbors': 3, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:01,876] Trial 18 finished with value: 0.987238455988456 and parameters: {'n_features': 8, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:01,932] Trial 19 finished with value: 0.9790301986025671 and parameters: {'n_features': 4, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:01,983] Trial 20 finished with value: 0.9868974044960886 and parameters: {'n_features': 6, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:02,032] Trial 21 finished with value: 0.9888499658236501 and parameters: {'n_features': 6, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:02,083] Trial 22 finished with value: 0.9872325225943648 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:02,131] Trial 23 finished with value: 0.98730111263006 and parameters: {'n_features': 5, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:02,179] Trial 24 finished with value: 0.9888499658236501 and parameters: {'n_features': 6, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:02,229] Trial 25 finished with value: 0.9888499658236501 and parameters: {'n_features': 6, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:02,275] Trial 26 finished with value: 0.9872325225943648 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:02,316] Trial 27 finished with value: 0.9848660476949952 and parameters: {'n_features': 5, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:02,364] Trial 28 finished with value: 0.9860183128275233 and parameters: {'n_features': 9, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:02,411] Trial 29 finished with value: 0.9654847345636819 and parameters: {'n_features': 3, 'n_neighbors': 4, 'weights': 'distance'}. Best is trial 1 with value: 0.9888499658236501.
[I 2025-11-24 20:39:02,421] A new study created in memory with name: no-name-ba450e1d-7031-4be9-925d-f1094275882e
[I 2025-11-24 20:39:02,461] Trial 0 finished with value: 0.9915052783473837 and parameters: {'n_features': 5, 'penalty': 'l1'}. Best is trial 0 with value: 0.9915052783473837.
[I 2025-11-24 20:39:02,518] Trial 1 finished with value: 0.9921413381939697 and parameters: {'n_features': 6, 'penalty': None}. Best is trial 1 with value: 0.9921413381939697.
[I 2025-11-24 20:39:02,587] Trial 2 finished with value: 0.9921413381939697 and parameters: {'n_features': 6, 'penalty': None}. Best is trial 1 with value: 0.9921413381939697.

Fold 4 completed.

[I 2025-11-24 20:39:02,635] Trial 3 finished with value: 0.9915052783473837 and parameters: {'n_features': 5, 'penalty': 'l1'}. Best is trial 1 with value: 0.9921413381939697.
[I 2025-11-24 20:39:02,690] Trial 4 finished with value: 0.9924622161464267 and parameters: {'n_features': 6, 'penalty': 'l1'}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:02,786] Trial 5 finished with value: 0.9905217589428116 and parameters: {'n_features': 4, 'penalty': 'l2'}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:02,836] Trial 6 finished with value: 0.9912888281309333 and parameters: {'n_features': 5, 'penalty': 'l1'}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:02,884] Trial 7 finished with value: 0.9898695602642972 and parameters: {'n_features': 3, 'penalty': 'l2'}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:02,936] Trial 8 finished with value: 0.9903242955874536 and parameters: {'n_features': 7, 'penalty': None}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:02,987] Trial 9 finished with value: 0.9916135034556088 and parameters: {'n_features': 5, 'penalty': 'l2'}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:03,033] Trial 10 finished with value: 0.9915071770334929 and parameters: {'n_features': 9, 'penalty': 'l1'}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:03,090] Trial 11 finished with value: 0.9903242955874536 and parameters: {'n_features': 7, 'penalty': None}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:03,144] Trial 12 finished with value: 0.98903129034708 and parameters: {'n_features': 8, 'penalty': None}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:03,209] Trial 13 finished with value: 0.9903242955874536 and parameters: {'n_features': 7, 'penalty': None}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:03,253] Trial 14 finished with value: 0.9924622161464267 and parameters: {'n_features': 6, 'penalty': 'l1'}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:03,296] Trial 15 finished with value: 0.9913970532391584 and parameters: {'n_features': 8, 'penalty': 'l1'}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:03,351] Trial 16 finished with value: 0.9897632338421815 and parameters: {'n_features': 3, 'penalty': 'l1'}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:03,401] Trial 17 finished with value: 0.9924622161464267 and parameters: {'n_features': 6, 'penalty': 'l1'}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:03,445] Trial 18 finished with value: 0.9903053087263615 and parameters: {'n_features': 4, 'penalty': 'l1'}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:03,486] Trial 19 finished with value: 0.9911806030227084 and parameters: {'n_features': 8, 'penalty': 'l1'}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:03,536] Trial 20 finished with value: 0.9924622161464267 and parameters: {'n_features': 6, 'penalty': 'l1'}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:03,577] Trial 21 finished with value: 0.9924622161464267 and parameters: {'n_features': 6, 'penalty': 'l1'}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:03,621] Trial 22 finished with value: 0.9913970532391584 and parameters: {'n_features': 7, 'penalty': 'l1'}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:03,666] Trial 23 finished with value: 0.9903053087263615 and parameters: {'n_features': 4, 'penalty': 'l1'}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:03,707] Trial 24 finished with value: 0.9924622161464267 and parameters: {'n_features': 6, 'penalty': 'l1'}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:03,759] Trial 25 finished with value: 0.9919362800941748 and parameters: {'n_features': 7, 'penalty': 'l2'}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:03,805] Trial 26 finished with value: 0.9915052783473837 and parameters: {'n_features': 5, 'penalty': 'l1'}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:03,851] Trial 27 finished with value: 0.9924622161464267 and parameters: {'n_features': 6, 'penalty': 'l1'}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:03,903] Trial 28 finished with value: 0.9915071770334929 and parameters: {'n_features': 9, 'penalty': 'l1'}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:03,960] Trial 29 finished with value: 0.9915052783473837 and parameters: {'n_features': 5, 'penalty': 'l1'}. Best is trial 4 with value: 0.9924622161464267.
[I 2025-11-24 20:39:03,971] A new study created in memory with name: no-name-b2f1eff7-8a58-4bfe-8af3-56e29cd9552a
[I 2025-11-24 20:39:04,021] Trial 0 finished with value: 0.9886506037821828 and parameters: {'n_features': 9, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 0 with value: 0.9886506037821828.
[I 2025-11-24 20:39:04,069] Trial 1 finished with value: 0.9785021265284424 and parameters: {'n_features': 4, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 0 with value: 0.9886506037821828.
[I 2025-11-24 20:39:04,117] Trial 2 finished with value: 0.9747322852586009 and parameters: {'n_features': 4, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 0 with value: 0.9886506037821828.
[I 2025-11-24 20:39:04,159] Trial 3 finished with value: 0.9862952836637048 and parameters: {'n_features': 9, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 0 with value: 0.9886506037821828.
[I 2025-11-24 20:39:04,202] Trial 4 finished with value: 0.9889695830485306 and parameters: {'n_features': 8, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 4 with value: 0.9889695830485306.
[I 2025-11-24 20:39:04,243] Trial 5 finished with value: 0.9801454393559655 and parameters: {'n_features': 5, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 4 with value: 0.9889695830485306.
[I 2025-11-24 20:39:04,284] Trial 6 finished with value: 0.9797220323536113 and parameters: {'n_features': 5, 'n_neighbors': 3, 'weights': 'uniform'}. Best is trial 4 with value: 0.9889695830485306.
[I 2025-11-24 20:39:04,325] Trial 7 finished with value: 0.9731658692185008 and parameters: {'n_features': 3, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 4 with value: 0.9889695830485306.
[I 2025-11-24 20:39:04,366] Trial 8 finished with value: 0.9803580922001975 and parameters: {'n_features': 5, 'n_neighbors': 4, 'weights': 'uniform'}. Best is trial 4 with value: 0.9889695830485306.
[I 2025-11-24 20:39:04,409] Trial 9 finished with value: 0.9869446343130553 and parameters: {'n_features': 6, 'n_neighbors': 4, 'weights': 'distance'}. Best is trial 4 with value: 0.9889695830485306.
[I 2025-11-24 20:39:04,459] Trial 10 finished with value: 0.9807976380344801 and parameters: {'n_features': 7, 'n_neighbors': 3, 'weights': 'distance'}. Best is trial 4 with value: 0.9889695830485306.
[I 2025-11-24 20:39:04,522] Trial 11 finished with value: 0.9886506037821828 and parameters: {'n_features': 9, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 4 with value: 0.9889695830485306.
[I 2025-11-24 20:39:04,598] Trial 12 finished with value: 0.9879120148856991 and parameters: {'n_features': 8, 'n_neighbors': 4, 'weights': 'distance'}. Best is trial 4 with value: 0.9889695830485306.
[I 2025-11-24 20:39:04,672] Trial 13 finished with value: 0.9889695830485306 and parameters: {'n_features': 8, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 4 with value: 0.9889695830485306.
[I 2025-11-24 20:39:04,747] Trial 14 finished with value: 0.9833409280777701 and parameters: {'n_features': 7, 'n_neighbors': 4, 'weights': 'distance'}. Best is trial 4 with value: 0.9889695830485306.
[I 2025-11-24 20:39:04,828] Trial 15 finished with value: 0.9889695830485306 and parameters: {'n_features': 8, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 4 with value: 0.9889695830485306.
[I 2025-11-24 20:39:04,881] Trial 16 finished with value: 0.989242993848257 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 16 with value: 0.989242993848257.
[I 2025-11-24 20:39:04,932] Trial 17 finished with value: 0.9807976380344801 and parameters: {'n_features': 7, 'n_neighbors': 3, 'weights': 'distance'}. Best is trial 16 with value: 0.989242993848257.
[I 2025-11-24 20:39:04,990] Trial 18 finished with value: 0.9865193286245919 and parameters: {'n_features': 6, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 16 with value: 0.989242993848257.
[I 2025-11-24 20:39:05,039] Trial 19 finished with value: 0.9833409280777701 and parameters: {'n_features': 7, 'n_neighbors': 4, 'weights': 'distance'}. Best is trial 16 with value: 0.989242993848257.
[I 2025-11-24 20:39:05,094] Trial 20 finished with value: 0.9879120148856991 and parameters: {'n_features': 8, 'n_neighbors': 4, 'weights': 'distance'}. Best is trial 16 with value: 0.989242993848257.
[I 2025-11-24 20:39:05,145] Trial 21 finished with value: 0.9889695830485306 and parameters: {'n_features': 8, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 16 with value: 0.989242993848257.
[I 2025-11-24 20:39:05,193] Trial 22 finished with value: 0.9889695830485306 and parameters: {'n_features': 8, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 16 with value: 0.989242993848257.
[I 2025-11-24 20:39:05,237] Trial 23 finished with value: 0.989242993848257 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 16 with value: 0.989242993848257.
[I 2025-11-24 20:39:05,280] Trial 24 finished with value: 0.9865155312523732 and parameters: {'n_features': 6, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 16 with value: 0.989242993848257.
[I 2025-11-24 20:39:05,330] Trial 25 finished with value: 0.989242993848257 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 16 with value: 0.989242993848257.
[I 2025-11-24 20:39:05,389] Trial 26 finished with value: 0.9865193286245919 and parameters: {'n_features': 6, 'n_neighbors': 5, 'weights': 'uniform'}. Best is trial 16 with value: 0.989242993848257.
[I 2025-11-24 20:39:05,440] Trial 27 finished with value: 0.9833409280777701 and parameters: {'n_features': 7, 'n_neighbors': 4, 'weights': 'distance'}. Best is trial 16 with value: 0.989242993848257.
[I 2025-11-24 20:39:05,493] Trial 28 finished with value: 0.9865155312523732 and parameters: {'n_features': 6, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 16 with value: 0.989242993848257.
[I 2025-11-24 20:39:05,547] Trial 29 finished with value: 0.989242993848257 and parameters: {'n_features': 7, 'n_neighbors': 5, 'weights': 'distance'}. Best is trial 16 with value: 0.989242993848257.

Fold 5 completed.

{'accuracy_lr': np.float64(0.9570785070785073),
 'accuracy_knn': np.float64(0.9552606177606178),
 'precission_lr': np.float64(0.946943914139036),
 'precission_knn': np.float64(0.9332475635538596),
 'recall_lr': np.float64(0.9369337979094077),
 'recall_knn': np.float64(0.9465737514518002),
 'f1_lr': np.float64(0.9413093848017888),
 'f1_knn': np.float64(0.9396706351707298)}

In [55]:
import scipy.stats as stats

In [ ]:
def mcnemar_test(y_true, y_pred1, y_pred2):
    correct1 = (y_pred1 == y_true)
    correct2 = (y_pred2 == y_true)

    n00 = np.sum((correct1 == False) & (correct2 == False))
    n01 = np.sum((correct1 == False) & (correct2 == True))
    n10 = np.sum((correct1 == True) & (correct2 == False))
    n11 = np.sum((correct1 == True) & (correct2 == True))

    contingency_table = np.array([[n00, n01],
                                  [n10, n11]])
    
    statistic = (abs(n01- n10) - 1)**2 / (n01 + n10) if (n01 + n10) != 0 else 0.0

    p_value = 1 - stats.chi2.cdf(statistic, df=1)

    return p_value, contingency_table

In [57]:
preds_lr_final = pipeline.predict(X_val)
preds_knn_final = pipeline.predict(X_val)

p_value, contingency_table = mcnemar_test(y_val, preds_lr_final, preds_knn_final)

print("Contingency Table:")
print(contingency_table)
print(f"P-value: {p_value}")

if p_value < 0.05:
    print("Różnica jest statystycznie istotna.")
else:
    print("Różnica nie jest statystycznie istotna.")

Contingency Table:
[[  1   0]
 [  0 139]]
P-value: 1.0
Różnica nie jest statystycznie istotna.